version: '3.8'

services:
  # Japanese AI Tutor Application
  japanese-tutor:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - tutor-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - tutor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Uncomment the following if you don't have NVIDIA GPU
    # Remove the deploy section above and uncomment this:
    # deploy:
    #   resources:
    #     limits:
    #       memory: 4G

  # Model Initialization Service
  model-init:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - tutor-network
    environment:
      - OLLAMA_HOST=ollama:11434
    entrypoint: >
      sh -c "
        echo 'Waiting for Ollama to be ready...' &&
        sleep 10 &&
        echo 'Pulling llama3:8b model...' &&
        ollama pull llama3:8b &&
        echo 'Model pulled successfully!'
      "
    restart: "no"

volumes:
  ollama-data:
    driver: local

networks:
  tutor-network:
    driver: bridge
